### ISSUE TITLE
Blog post and documentation about JS SDK Plugin structure 

### ISSUE THREAD

**Issue by mekya** [ant-media/ant-media-documentation#12]

**Comment by timantmedia** [comment]
@mustafaboleken is there a JavaScript SDK plugin structure? I mean, what does this mean, I am unsure.

**Comment by mekya** [comment]
Hi @timantmedia,

Yes, there is a JavaScript SDK plugin structure. Virtual background uses this structure to work. We've implemented this to manage the dependencies easily. 

Check this out
https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/js/video-effect.js 

[Plugin registers itself](https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/js/video-effect.js#L397) and define new methods to the WebRTCAdaptor.
WebRTCAdaptor also support event callbacks through [addEventListener](https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/js/webrtc_adaptor.js#L384) 

FYI
