### ISSUE TITLE
Review the documentation and enlist any missing/obsolete parts.

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/ant-media-documentation#16]
There are two primary objectives of this documentation review:
1. Find any missing and obsolete parts in the documentation.
2. Try all the documents and find out how they can be made easier to understand and end-user friendly.

**Comment by Mohit-3196** [comment]
https://docs.google.com/document/d/1TQ1RXX5VFzvkYS1F5dMMJ38Q3qitj2dUhY2g2VEoxNI/edit?usp=sharing

**Comment by Mohit-3196** [comment]
Continuing the existing review and update the documents.
Next phase is to try the developer documents and make it simpler for regular users to understand and execute.

**Comment by timantmedia** [comment]
@Mohit-3196 what items in the document have been added already to the documentation?

**Comment by Mohit-3196** [comment]
HI @timantmedia ,
This task was nullified after all of us were given specific sections to work on. So, we can check this issue thread #79 for the updates.

**Comment by asharamseervi** [comment]
As it is merged with another issue, I'm closing it. Kindly refer: https://github.com/ant-media/ant-media-documentation/issues/79
