### ISSUE TITLE
Documentation for VoD upload script 4087

### ISSUE THREAD

**Issue by mekya** [ant-media/ant-media-documentation#19]
Prepare documentation for this feature ant-media/Ant-Media-Server#4087

**Comment by timantmedia** [comment]
@mekya could you explain this feature? How is it different to using the rest api `/v2/vods/create` and what exactly needs documenting? I do not fully understand, do you mind explaining and I can create this.

**Comment by mekya** [comment]
hi @timantmedia ,

Is it clear for now?

Thank you @asharamseervi

**Comment by timantmedia** [comment]
Ceate a document or blog post based on this answer https://github.com/ant-media/Ant-Media-Server/issues/3983

**Comment by timantmedia** [comment]
Already in FAQ https://github.com/orgs/ant-media/discussions/4888
