### ISSUE TITLE
Update the Flutter SDK document

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/ant-media-documentation#232]
### Link to the documentation page or resource

https://antmedia.io/docs/guides/developer-sdk-and-api/sdk-integration/flutter-sdk/

### Describe the bug

Update the Flutter SDK document to use the same structure as the Android and iOS SDKs.

**Comment by mustafaboleken** [comment]
Ready to review https://github.com/ant-media/ant-media-documentation/pull/249
