### ISSUE TITLE
Update the Playlist document

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/ant-media-documentation#234]
### Link to the documentation page or resource

https://antmedia.io/docs/guides/publish-live-stream/playlist/

### Describe the bug

Update and improve the playlist document by taking references from the below discussion.
https://github.com/orgs/ant-media/discussions/6015 - It includes playlist skip part as a new feature

**Comment by Mohit-3196** [comment]
https://github.com/ant-media/ant-media-documentation/pull/253
