### ISSUE TITLE
Update CMAF (DASH) document

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/ant-media-documentation#239]
### Link to the documentation page or resource

https://antmedia.io/docs/guides/playing-live-stream/dash-playing-cmaf/

### Describe the bug

It seems the formatting of this document has been disturbed during any update or refactoring. Improve it and also add any information that is missing.

**Comment by Mohit-3196** [comment]
https://github.com/ant-media/ant-media-documentation/pull/299
