### ISSUE TITLE
Refactor TURN and STUN server documentation

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/ant-media-documentation#251]
### Link to the documentation page or resource

https://antmedia.io/docs/guides/advanced-usage/turn-and-stun-installation/coturn-quick-installation/

### Describe the bug

- Remove the [sample page part](https://antmedia.io/docs/guides/advanced-usage/turn-and-stun-installation/coturn-quick-installation/#how-to-add-turn-server-to-ant-media-sample-pages), as we do not recommend adding it there anymore. Instead of it, we can define in STUN configuration document how to add it on client sides like JS SDK, Android SDK, IOS SDK, etc.
- Refactor STUN server configuration document and move it to the [TURN server category](https://antmedia.io/docs/category/turn--stun-installation/).

**Comment by lastpeony** [comment]
https://github.com/ant-media/ant-media-documentation/pull/290

**Comment by Mohit-3196** [comment]
Done
