### ISSUE TITLE
Update the Web Panel Blogpost

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/ant-media-documentation#273]
### Link to the documentation page or resource

https://antmedia.io/how-to-use-ant-media-server-web-panel/

### Describe the bug

This is an old blog post, so it needs to be updated as per new changes on the Web Panel.

**Comment by amarantmeida** [comment]
Updated the blogpost, Yash to review it further. 
https://antmedia.io/how-to-use-ant-media-server-web-panel/
