### ISSUE TITLE
Refactor AWS CloudFormation cluster update

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/ant-media-documentation#285]
### Link to the documentation page or resource

https://antmedia.io/docs/guides/clustering-and-scaling/aws/updating-ams-with-cloudformation/

### Describe the bug

We need to revisit this document to ensure a smooth upgrade of the CloudFormation cluster on AWS. There is a [blogpost](https://antmedia.io/upgrade-ant-media-server-on-aws-cluster/) for that as well.

We need to modify the document according to the use of launch templates now instead of launch configurations.

Customer raised this as well:

https://github.com/orgs/ant-media/discussions/6477

**Comment by Mohit-3196** [comment]
Merged https://github.com/ant-media/ant-media-documentation/pull/382
