### ISSUE TITLE
Update Manual clustering documentation

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/ant-media-documentation#303]
### Link to the documentation page or resource

https://antmedia.io/docs/guides/clustering-and-scaling/manual-configuration/cluster-installation/

### Describe the bug

- Review the flow of the documentation, formatting, etc.

- In [installation part of Origin and Edge group](https://antmedia.io/docs/guides/clustering-and-scaling/manual-configuration/cluster-installation/#install-the-origin-and-edge-groups), make it more clear how to first install and then explain about changing to cluster mode.

- Check the installation and configuration of Nginx proxy (mainly using the installation script)

**Comment by filip-ams** [comment]
Open pr for this: https://github.com/ant-media/ant-media-documentation/pull/338
