### ISSUE TITLE
Add Playlist scheduling and easy adding of VOD to the playlist document

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/ant-media-documentation#312]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet.

### Summary

The upcoming version 2.10.0 supports playlist scheduling so add it to the playlist document.

### Why is it needed?

It is needed to add new features to the document

### Related issue(s)/PR(s)

https://github.com/ant-media/Ant-Media-Server/issues/6243

**Comment by Mohit-3196** [comment]
#328
