### ISSUE TITLE
Refactor AMS application configuration document

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/ant-media-documentation#327]
### Link to the documentation page or resource

https://antmedia.io/docs/guides/configuration-and-testing/ams-application-configuration/

### Describe the bug

Refactor and add the document to change Application settings using the Rest APIs as well

**Comment by Mohit-3196** [comment]
https://github.com/ant-media/ant-media-documentation/pull/340

**Comment by filip-ams** [comment]
Reviewed/Published
