### ISSUE TITLE
Refactor IP camera blog post

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/ant-media-documentation#346]
### Link to the documentation page or resource

https://antmedia.io/ip-camera-streaming-with-ant-media-server/

### Describe the bug

1. Add IP camera streaming with LL-HLS part as LL-HLS is a new feature.
2. Add [Dynamic Pulling](https://antmedia.io/docs/guides/publish-live-stream/ip-cameras-and-external-resources/#dynamic-stream-pulling) point explanation to the **Why should you choose Ant Media Server** part of the blog

**Comment by filip-ams** [comment]
Added the LL-HLS part: https://antmedia.io/ip-camera-streaming-with-ant-media-server/
