### ISSUE TITLE
Review the documents and make user friendly - Phase 1

### ISSUE THREAD

**Issue by mekya** [ant-media/ant-media-documentation#35]

**Comment by Mohit-3196** [comment]
For phase 1, I have started testing SDKs.
1. Android SDK
Android SDK works for me but the document is outdated.
I plan to finish testing all the samples this week and then work to update the document.

2. Flutter SDK
Flutter SDK also works for me and the document is mostly valid. Once the build starts to pass, I will update the document for version 1.0.0 currently it mentions 0.0.8

After completing these, I will start with React Native SDK and WebRTC Play Page Creation Tutorial
