### ISSUE TITLE
Fix broken document links

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/ant-media-documentation#360]
### Link to the documentation page or resource

Links are in the excel sheets

### Describe the bug

Fix broken document links

**Comment by Mohit-3196** [comment]
I have fixed some that I found in the first sheet: https://github.com/ant-media/ant-media-documentation/pull/368

**Comment by yashtandon113** [comment]
Document broken links are corrected but somehow still few of the links are showing 404 even after redirecting to correct link or may be it is not redirecting well.

Their are a lot of links in the sheet that need to be redirected from the website to documents or blogs.
