### ISSUE TITLE
Refactor Codecs document and add HEVC (H265) codec

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/ant-media-documentation#371]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet.

### Summary

Refactor the [Codecs document](https://antmedia.io/docs/guides/configuration-and-testing/webrtc-codecs/)

- Refactor the current H264 and VP8 codec parts
- Add HEVC (H265) codec details and how to play it

### Why is it needed?

Currently, their is no trace of H265 codec in documents so it needs to be added

**Comment by Mohit-3196** [comment]
It's in progress.

**Comment by Mohit-3196** [comment]
https://github.com/ant-media/ant-media-documentation/pull/395
