### ISSUE TITLE
Cluster deployment on GCP

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/ant-media-documentation#388]
### Is there an existing issue for this?

- [X] I have searched existing issues; it hasn't been reported yet.

### Summary

This document request is a part of this [parent document](https://github.com/ant-media/ant-media-documentation/issues/387.) task for GCP.

https://antmedia.io/scale-ant-media-server-google-cloud-platform-guide/

### Why is it needed?

It is needed to add GCP-related documents in the AMS documentation

**Comment by filip-ams** [comment]
For some reason I couldn't link my pr via the side menu so here it is:
https://github.com/ant-media/ant-media-documentation/pull/403
