### ISSUE TITLE
Review AWS ECS documents

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/ant-media-documentation#402]
### Link to the documentation page or resource

https://antmedia.io/docs/category/aws/

### Describe the bug

Create a sub category like AWS ECS under the AWS and refactor and review the AWS ECS documents.

- [x] https://antmedia.io/docs/guides/clustering-and-scaling/aws/running-ams-container-at-ecs/

- [x] https://antmedia.io/docs/guides/clustering-and-scaling/aws/scaling-at-aws-ecs-fargate/

**Comment by Mohit-3196** [comment]
https://github.com/ant-media/ant-media-documentation/pull/419

**Comment by Mohit-3196** [comment]
https://github.com/ant-media/ant-media-documentation/pull/422
