### ISSUE TITLE
Write Blogpost about helm deployment and Update documentation

### ISSUE THREAD

**Issue by mekya** [ant-media/ant-media-documentation#7]

**Comment by muratugureminoglu** [comment]
> Update the documentation for antmedia.io/docs @muratugureminoglu

https://github.com/ant-media/ant-media-documentation/pull/9

**Comment by timantmedia** [comment]
Blog post published

**Comment by asharamseervi** [comment]
Documentation and blogpost published, requesting assignee to review it if everything looks good, they may close the issue.

**Comment by mekya** [comment]
Then I'm closing the issue.
