### ISSUE TITLE
Update iOS documentation according to the new blog post

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/ant-media-documentation#77]

**Comment by Mohit-3196** [comment]
https://github.com/ant-media/ant-media-documentation/pull/78

**Comment by asharamseervi** [comment]
Hi @Mohit-3196, I have reviewed and noticed iOS SDK Developer Guide and User Guide has the same title name; some user may find it contradictory as both files reside in the same directory.

- https://deploy-preview-78--ant-media-documentation.netlify.app/guides/developer-sdk-and-api/sdk-integration/ios-sdk/
- https://deploy-preview-78--ant-media-documentation.netlify.app/guides/developer-sdk-and-api/sdk-integration/ios-sdk-user-guide/

Just thinking it loud, we should either rename the title or create a new section for the SDKs User Guide. This would simplify the guide and make it easier for users to distinguish between the integration guide and the user guide. Following the example of the iOS SDK User Guide. Similarly, other SDKs could be simplified by adding a "user guide" to the title in the future if we create user guides.

**Comment by Mohit-3196** [comment]
Hi @asharamseervi ,
Thank you for your review and suggestions.
Initially, I was thinking to create a separate document for this simplified user guide for iOS SDK and hence named it ios-sdk-user-guide as it is more detailed and covers publish and play for now mainly where the existing doc talks about other samples like data channel and P2P.

But maybe I missed a trick and it seems that I can just update the existing doc for these publish and play sections so let me merge this into the existing document and update the publish and play sections.
Let me know if that would be OK or if we should have two sections each for the developer and user.

Thank you again
