### ISSUE TITLE
Re-organize Scaling Documentation

### ISSUE THREAD

**Issue by timantmedia** [ant-media/ant-media-documentation#84]
![Image](https://user-images.githubusercontent.com/3456251/241711179-535e03f9-41f1-4908-83ca-b46b6a35ca18.png)

It does not seem consistent. Here are some points
- `
AWS
Azure
.....
Scaling Ant Media Server with Alibaba ...
`
Use the same convention.

- Scaling with Mongodb Atlas is database connection type. It's not directly a scaling solution. It should appear somewhere else.
-  Load Balancing is mostly related to Cluster and MultiLevelCluster. It's not in the correct location. It shows like a full Scaling solution

**Comment by timantmedia** [comment]
PR here https://github.com/ant-media/ant-media-documentation/pull/85 changes made as in the screenshot below.

I renamed Alibaba and created a new sub directory for guides that explain how to manually install a cluster. This is where the load balancer documentation has been added. 

I've also created a separate directory outside of the clustering section for support databases. 



![Image](https://github.com/ant-media/ant-media-documentation/assets/121940452/8d33d2e3-085b-4792-8714-de6077dba770)

**Comment by asharamseervi** [comment]
This change looks more organized. I appreciate your efforts. As we are going through many architecture-level changes and it is considered breaking changes; it'll introduce 404 errors; I'm going to introduce a _redirect_ file where we can redirect 301 from the previous location to the new one.

Requesting you, add redirects by appending them to existing URLs.

**Comment by timantmedia** [comment]
@asharamseervi how can I add redirects?

**Comment by asharamseervi** [comment]
Ah, I couldn't be able to manage to implement _redirect; I'll take this on priority. We can keep this task in-review for next week.

**Comment by timantmedia** [comment]
I did a git rebase on this branch and merged the changed. I do not know if this caused any issues with other peoples changes further back or not. I need someone to review it for me https://github.com/ant-media/ant-media-documentation/pull/85.

**Comment by mekya** [comment]
Umut is going to review it.

**Comment by umtcylmz** [comment]
it makes sense that we have different heading for manual installation and the other cloud provider offerings @mekya

**Comment by timantmedia** [comment]
Umut reviewed this and said:

`Yes it make sense that we have different heading for manual installation and the other cloud provider offerings
`

I've added @yashtandon113 and @Mohit-3196 as reviewers on the PR https://github.com/ant-media/ant-media-documentation/pull/85.

The only concern is that the documents have been moved so the URLs have changed so the old URLs will redirect back to antmedia.io if the route is not found. 

So before merging we need to install a URL redirect plugin https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-client-redirects

**Comment by timantmedia** [comment]
Currently creating the necessary redirects using the plugin will create PR this week and then merge the menu changes.
